// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MotorVehicle
{
    class Program
    {
        static void Main(string[] args)
        {
            // predict with default option.
            var modelOutput = MotorVehicle.Predict();
            Console.WriteLine(string.Join(",", modelOutput.X));

            // predict next 5 periods
            modelOutput = MotorVehicle.Predict(horizon: 5);
            Console.WriteLine(string.Join(",", modelOutput.X));

            // update and predict model
            // TBD
        }
    }
}

